

```{r}
# run config 
#source("~/MGG Dropbox/Projects/divRBP/code/protein-mosaicism/paper-figures/1.config.R")
source("~/MGG Dropbox/Projects/divRBP/code/protein-mosaicism/paper-figures/1.config.R")
SHINY_DATA_PATH = "~/MGG Dropbox/Projects/divRBP/code/protein-mosaicism/shiny-server/Phage.Domain.Lookup/data/"


ecod.domains.hits = data.table::fread(sprintf("%secod.domains.hits.txt",OUTPUT.DATA.PATH))
families = data.table::fread(file = sprintf("%sfamilies.txt", OUTPUT.DATA.PATH))
ecod_id_to_names_map = data.table::fread(sprintf("%secod_id_to_names_map.txt",OUTPUT.DATA.PATH)) %>% as.data.frame()
surely.annotated.proteins.including.multi.annot = data.table::fread( sprintf("%ssurely.annotated.proteins.including.multi.annot",OUTPUT.DATA.PATH))
included.category.sizes = data.table::fread(sprintf("%sincluded.category.sizes",OUTPUT.DATA.PATH))
# disregard the ones with multiple annotations
surely.annotated.proteins = surely.annotated.proteins.including.multi.annot %>% filter(num.annots == 1 & include == "TRUE")
```

```{r}
surely.annotated.ecod.domains.high.confidence = ecod.domains.hits %>% 
  select(qname, qstart, qend, qlength, sstart, send, slength, x_id, h_id, t_id, f_id) %>%
  # note that some families may be unclassified i.e. d_id = NA
  inner_join(surely.annotated.proteins)  %>%  # take the conservatively defined domains onlu
  inner_join(included.category.sizes, by = c("annotation.index")) 
```


#SHINY PLOTS: DOMAINS WITHIN FUNCTIONS
```{r}

tile.data.list = list()
tile.data.multi.list = list()
i=0
domain_levels = c("T", "H")
for (this.domain.level in domain_levels) {
this.domain.level.id = paste0(tolower(this.domain.level), "_id")
for (this.category in unique(surely.annotated.ecod.domains.high.confidence$category)) {
  domain.position.plots.this.category = list()
  domain.combination.plots.this.category = list()
  this.category.annotations = surely.annotated.ecod.domains.high.confidence %>% 
    filter(category == this.category) %>% 
    pull(annotation) %>% 
    unique()

  for (this.annotation in this.category.annotations) {
    domains.within.this.annotation = surely.annotated.ecod.domains.high.confidence %>% 
      filter(category == this.category & annotation == this.annotation) %>% 
        select(qname, annotation, qlength, qstart, qend, domain = this.domain.level.id)  %>% 
        group_by(qname) %>%
        arrange(qstart) %>%
      # HACK , sort by teh first domain
        mutate(family =  domain[1],
               num.domains = n_distinct(domain),
               all.domains = paste0(sort(unique(domain)), collapse = "_and_")) %>%
        ungroup() 
    
    if (nrow(domains.within.this.annotation) > 0) {
      i=i+1
      tile.data = Get.Domain.Positions.Data(
        domains.within.this.annotation) %>%
        mutate(annotation = this.annotation,
               category = this.category,
               domain.level = this.domain.level)
        tile.data.list[[i]] = tile.data
        
      tile.data.multi = Get.Domain.Positions.Data(
        domains.within.this.annotation %>%
          filter(num.domains > 1) %>%
          group_by(all.domains) %>%
          mutate(repr.qname = qname[1]) %>%
          ungroup() %>%
          filter(repr.qname == qname)) %>%
        mutate(annotation = this.annotation,
               category = this.category,
               domain.level = this.domain.level)
      tile.data.multi.list[[i]] = tile.data.multi
          
    }
  }
}
}

    tile.data = do.call('rbind', tile.data.list) %>%
      left_join(ecod_id_to_names_map %>% 
                  select(domain = id, domain_name = name, domain.level = level) %>%
                  rbind(expand.grid(domain.level = unique(ecod_id_to_names_map$level), 
                                    domain = c("undetected", "multiple domains")) %>%
                                   mutate(domain_name = domain))) %>%
      rowwise() %>%
      mutate(domain = if_else(domain == "undetected" | domain == "multiple domains", 
                            domain,
                            paste0(domain_name, " [", domain, "]"))) %>%
      left_join(families, by = "qname")
    
    tile.data.multi = do.call('rbind', tile.data.multi.list) %>%
      left_join(ecod_id_to_names_map %>% 
                  select(domain = id, domain_name = name, domain.level = level) %>%
                  rbind(expand.grid(domain.level = unique(ecod_id_to_names_map$level), 
                                    domain = c("undetected", "multiple domains")) %>%
                                   mutate(domain_name = domain))) %>%
      rowwise() %>%
      mutate(domain = if_else(domain == "undetected" | domain == "multiple domains", 
                            domain,
                            paste0(domain_name, " [", domain, "]"))) %>%
      left_join(families, by = "qname")
    

saveRDS(tile.data.multi, sprintf("%smultiple_domains.domain.positions.Rds", SHINY_DATA_PATH))
saveRDS(tile.data, sprintf("%sdomain.positions.Rds", SHINY_DATA_PATH))
annnotations.and.categories = tile.data %>% distinct(category, annotation, domain.level)
saveRDS(annnotations.and.categories, 
        sprintf("%sannnotations.and.categories.Rds", SHINY_DATA_PATH))
```

```{r, eval = FALSE}
for (this.category in unique(annnotations.and.categories$category)) {
    this.tile.data.multi = tile.data.multi %>% filter(category == this.category)
    this.tile.data = tile.data %>% filter(category == this.category)
    #Rds files are smaller
    saveRDS(this.tile.data.multi, sprintf("%smultiple_domains.domain.positions_%s.Rds", SHINY_DATA_PATH, this.category))
    saveRDS(this.tile.data, sprintf("%sdomain.positions_%s.Rds", SHINY_DATA_PATH, this.category))
}
a=1
```
