---
title: "5.optional_analyses"
author: "Bogna Smug"
date: '2022-12-16'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
recent.mosaicism.hhr = data.table::fread(file = sprintf("%srecent.mosaicism.hhr.txt",OUTPUT.DATA.PATH))

```


# All domains network
```{r}

ecod.domains.with.annotations$category[which(is.na(ecod.domains.with.annotations$category))] = "unknown"
  edh = ecod.domains.with.annotations %>%
    distinct(qname, t_id, category)
  # and we see what other doains coexist with these domains
  all.domain.network = edh %>%
    inner_join(edh, by = c("qname", "category")) %>%
    filter(t_id.x < t_id.y) %>%
    #rowwise() %>%
    #mutate(pair = paste(sort(c(t_id.x, t_id.y)), collapse = " AND ", sep = ""),
    #       category = selected_category) %>%
    group_by(t_id.x, t_id.y) %>%
    mutate(num.prot = n_distinct(qname)) %>%
    ungroup() %>%
    select(from = t_id.x, to = t_id.y, category, num.prot) %>%
    filter(num.prot >- 5) %>%
    distinct(from, to, category)


PHROG.COLOR.MAP_GENEARAL = c("integration and excision_general" = "#ffb300", 
                  "head and packaging_general" = "#d8f2d3", 
                  "transcription regulation_general" = "##cba1d1", 
                  "connector_general" = "#05f043",
                  "tail_general" = "#6c8c79",
                  "lysis_general" = "#d16d6e", 
                  "DNA, RNA and nucleotide metabolism_general" = "#8aa6bd", 
                  "other_general" = "#e0e0e0",
                  "moron, auxiliary metabolic gene and host takeover_general" = "##f5c9e0")
PHROG.COLOR.MAP2 = c(PHROG.COLOR.MAP, PHROG.COLOR.MAP_GENEARAL)

  all.domain.annotations = ecod.domains.with.annotations %>%
    distinct(t_id, annotation, category) %>%
    group_by(t_id) %>%
    mutate(num.annots = n_distinct(annotation[category != "unknown"]),
           num.categories = n_distinct(category[category != "unknown"])) %>%
    arrange(t_id) %>%
    summarise(category = if_else(
      all(num.categories == 0), "unknown", 
      if_else(all(num.categories >1), "multiple",
              if_else(all(num.annots > 1), paste0(category[category != "unknown"][1], "_general") ,category[1])))) %>%
    left_join(stack(PHROG.COLOR.MAP2) %>% select(color = values, category = ind), by = "category") %>%
    mutate(multi = category == "multiple")  %>%
    mutate(color = if_else(multi, "#000000", color)) %>%
    mutate(color = if_else(category == "unknown", "#D3D3D3", color)) %>%
    #mutate(color = if_else(grepl("general_", annotation) & !multi, adjustcolor(color, alpha.f = 0.2), color)) %>%
    select(node = t_id, category, color)
  
  all.domain.network.metadata = data.frame(node = unique(c(all.domain.network$from, all.domain.network$to))) %>%
    left_join(ecod_id_to_names_map %>% filter(level == "T") %>% select(node = id, label = name)) %>%
    mutate(size = 1) %>%
    left_join(all.domain.annotations, by = "node")
  
data.table::fwrite(all.domain.network.metadata, sprintf("%sFigure5/all.domain.network.metadata.txt", OUTPUT.FIGURES.PATH))
data.table::fwrite(all.domain.network, sprintf("%sFigure5/all.domain.network.txt", OUTPUT.FIGURES.PATH))

```

# shiny plots for selected sequences
```{r, eval = FALSE}
dnap.seq = read.table("/Users/bognasmug/MGG Dropbox/Projects/divRBP/phage-pp-workdir-refseq-hhblits/dnap-uniclust.txt")
names(dnap.seq) = "qname"

    domains.within.this.annotation = surely.annotated.ecod.domains.high.confidence %>% 
      inner_join(dnap.seq) %>%
        select(qname, annotation.index, annotation, qlength, qstart, qend, domain = "t_id", family)  %>% 
        group_by(qname) %>%
        mutate(all.domains = paste0(sort(unique(domain)), collapse = "_and_"),
               # this is just used for ordering
               first.domain = domain[qstart == min(qstart)][1]) %>%
        ungroup() 

      tile.data.dnap = Get.Domain.Positions.Data(
        domains.within.this.annotation %>%
          # take only one representative per each domain combination and family combination
          group_by(all.domains, family) %>%
          mutate(first.domain = first.domain[1],
                  repr.qname = qname[1]) %>%
          ungroup() %>%
          filter(repr.qname == qname) %>%
        arrange(first.domain, family)) %>%
        mutate(annotation = "hypothetical DNA polymerase",
               domain.level = "T") %>%
        left_join(families, by = "qname") 

tile.data.dnap.domains = tile.data.dnap %>% distinct(domain)
tile.data.dnap$x.index <- sapply(1:nrow(tile.data.dnap), function(index){
  this.topology <- tile.data.dnap$domain[index]
  this.topology.x.index <- strsplit(this.topology, ".", fixed = T)[[1]][1] %>% as.character()
})



  x_index_ecod_map = ecod_id_to_names_map %>% 
                  filter(level == "X") %>%
                  mutate(id = as.character(id)) %>%
                  select(x.index = id, x_name = name) %>%
                  rbind(data.frame(x.index = c("undetected", "multiple domains")) %>%
                                   mutate(x_name = x.index))
  
    tile.data.dnap.final = tile.data.dnap %>%
      left_join(ecod_id_to_names_map %>% 
                  select(domain = id, domain_name = name, domain.level = level) %>%
                  rbind(expand.grid(domain.level = unique(ecod_id_to_names_map$level), 
                                    domain = c("undetected", "multiple domains")) %>%
                                   mutate(domain_name = domain))) %>%
      left_join(tile.data.dnap.domains) %>%
      left_join(x_index_ecod_map, by = "x.index") 
    
data.table::fwrite(tile.data.dnap.final, sprintf("%sFigure5/domain.positions.dnap.uniclust.txt", OUTPUT.FIGURES.PATH))
```


# recrent HGT on HHalign
```{r}
#check if hhalign confirms the recent mosaicism found above
recent_HGT_pairs_raw.90.confirmed = recent_HGT_pairs_raw.90 %>%
  inner_join(recent.mosaicism.hhr, by = c("qname", "sname", "pair")) %>%
  group_by(pair) %>%
  summarise(mosaic.90 = all(mosaic.pident90),
            mosaic.70 = all(mosaic.pident70))


recent_HGT_pairs_raw.90.confirmed.for.network = recent_HGT_pairs_raw.90 %>%
  inner_join(recent_HGT_pairs_raw.90.confirmed, by = "pair") %>%
  filter(mosaic.90) %>%
  select(qname, sname) %>%
  left_join(surely.annotated.proteins.from.included.categories %>% select(qname, qindex = annotation.index)) %>%
  left_join(surely.annotated.proteins.from.included.categories %>% select(sname = qname, sindex = annotation.index)) %>%
  #filter(qindex != sindex & !is.na(qindex) & !is.na(sindex)) %>%
  rowwise() %>%
  mutate(pair = paste(sort(c(qname, sname)), collapse = " AND ", sep = "")) %>%
  ungroup()

recent_HGT_pairs.90.confirmed = rbind( recent_HGT_pairs_raw.90.confirmed.for.network %>%
  select(from = qindex, to = sindex, pair),
  recent_HGT_pairs_raw.90.confirmed.for.network %>%
  select(to = qindex, from = sindex, pair)) %>%
  mutate(from = if_else(is.na(from),as.integer(0), from),
         to = if_else(is.na(to), as.integer(0), to)) %>%
  group_by(from, to) %>%
  summarise(num.prot.pairs = n_distinct(pair)) %>%
  ungroup() %>%
  filter(num.prot.pairs >= 2) %>%
  filter(from <= to) %>%
  distinct() 

data.table::fwrite(recent_HGT_pairs.90.confirmed, sprintf("%sFigure_Supplementary/FigS11_recent_HGT/recent_HGT_network_90_confirmed.txt", OUTPUT.FIGURES.PATH))

recent_HGT_pairs_raw.70.confirmed = recent_HGT_pairs_raw.70 %>%
  inner_join(recent.mosaicism.hhr, by = c("qname", "sname", "pair")) %>%
  group_by(pair) %>%
  summarise(mosaic.50 = all(mosaic.pident50),
            mosaic.70 = all(mosaic.pident70))


recent_HGT_pairs_raw.70.confirmed.for.network = recent_HGT_pairs_raw.70 %>%
  inner_join(recent_HGT_pairs_raw.70.confirmed, by = "pair") %>%
  filter(mosaic.70) %>%
  select(qname, sname) %>%
  left_join(surely.annotated.proteins.from.included.categories %>% select(qname, qindex = annotation.index)) %>%
  left_join(surely.annotated.proteins.from.included.categories %>% select(sname = qname, sindex = annotation.index)) %>%
  #filter(qindex != sindex & !is.na(qindex) & !is.na(sindex)) %>%
  rowwise() %>%
  mutate(pair = paste(sort(c(qname, sname)), collapse = " AND ", sep = "")) %>%
  ungroup()

recent_HGT_pairs.70.confirmed = rbind( recent_HGT_pairs_raw.70.confirmed.for.network %>%
  select(from = qindex, to = sindex, pair),
  recent_HGT_pairs_raw.70.confirmed.for.network %>%
  select(to = qindex, from = sindex, pair)) %>%
  mutate(from = if_else(is.na(from),as.integer(0), from),
         to = if_else(is.na(to), as.integer(0), to)) %>%
  group_by(from, to) %>%
  summarise(num.prot.pairs = n_distinct(pair)) %>%
  ungroup() %>%
  filter(num.prot.pairs >= 2) %>%
  filter(from <= to) %>%
  distinct() 

data.table::fwrite(recent_HGT_pairs.70.confirmed, sprintf("%sFigure_Supplementary/FigS11_recent_HGT/recent_HGT_network_70_confirmed.txt", OUTPUT.FIGURES.PATH))
```

```{r}
recent_HGT_pairs_raw.domain.data.all.pident70_confirmed = Get.Recent.HGT.Domains(
  recent_HGT_pairs_raw = recent_HGT_pairs_raw.70 %>%
    inner_join(recent_HGT_pairs_raw.70.confirmed, by = "pair") %>%
    filter(mosaic.70), 
  # note that technically pident and prob in the raw hhr.tabl may not be the same as within our summarised table we used before
  # make the hhr table symmetric so that every reprseq is seen on qname position
  hhr.table = rbind(recent.mosaicism.hhr %>% 
    select(qname, sname, qstart, qend, sstart, send, prob),
      recent.mosaicism.hhr %>% 
    select(qname = sname, sname = qname, qstart = sstart, qend = send, sstart = qstart, send=qend, prob)),
  surely.annotated.proteins.from.included.categories, 
  ecod.domains.hits)

recent_HGT_pairs_raw.domain.data.all.pident90_confirmed = Get.Recent.HGT.Domains(
  recent_HGT_pairs_raw = recent_HGT_pairs_raw.90 %>%
    inner_join(recent_HGT_pairs_raw.90.confirmed, by = "pair") %>%
    filter(mosaic.90), 
  # note that technically pident and prob in the raw hhr.tabl may not be the same as within our summarised table we used before
  # make the hhr table symmetric so that every reprseq is seen on qname position
  hhr.table = rbind(recent.mosaicism.hhr %>% 
    select(qname, sname, qstart, qend, sstart, send, prob),
      recent.mosaicism.hhr %>% 
    select(qname = sname, sname = qname, qstart = sstart, qend = send, sstart = qstart, send=qend, prob)),
  surely.annotated.proteins.from.included.categories, 
  ecod.domains.hits)


write.csv(recent_HGT_pairs_raw.domain.data.all.pident70_confirmed, sprintf("%sFigure_Supplementary/recent_HGT_domains.pident70_confirmed.csv", OUTPUT.FIGURES.PATH))
write.csv(recent_HGT_pairs_raw.domain.data.all.pident90_confirmed, sprintf("%sFigure_Supplementary/recent_HGT_domains.pident90_confirmed.csv", OUTPUT.FIGURES.PATH))
```

```{r}
text_size.x = 6
text_size.y = 6
recent_HGT_pairs_raw.domain.data.all.pident70 = read.csv(sprintf("%sFigure_Supplementary/recent_HGT_domains.pident70_confirmed.csv", OUTPUT.FIGURES.PATH))
recent_HGT_pairs_raw.domain.data.to.plot.all.pident70 = recent_HGT_pairs_raw.domain.data.all.pident70 %>%
  filter(n_pairs > 5)
recent_HGT_pairs_raw.domain.data.to.plot.all.pident70$t_name = factor(recent_HGT_pairs_raw.domain.data.to.plot.all.pident70$t_name, levels = unique(recent_HGT_pairs_raw.domain.data.to.plot.all.pident70$t_name))
p=ggplot(recent_HGT_pairs_raw.domain.data.to.plot.all.pident70) + geom_col(aes(x = t_name, y = n_pairs, fill = h_name), col = "black") +
  theme_bw() +
    theme(axis.text.x = element_text(angle=45, hjust =1,vjust=1, size = text_size.x),
        axis.text.y = element_text(hjust = 1, size = text_size.y),
        legend.position = "left") +
  scale_y_sqrt(breaks = c(2,10,25,50,100,150)) +
  xlab("") +
  ylab("Num. protein pairs")
ggsave(sprintf("%sFigure_Supplementary/recent_HGT_domains_pident70_confirmed.jpg", OUTPUT.FIGURES.PATH), p, width = 15, height = 7)


recent_HGT_pairs_raw.domain.data.to.plot.all.pident90 = read.csv(sprintf("%sFigure_Supplementary/recent_HGT_domains.pident90_confirmed.csv", OUTPUT.FIGURES.PATH))
recent_HGT_pairs_raw.domain.data.to.plot.all.pident90 = recent_HGT_pairs_raw.domain.data.to.plot.all.pident90 %>%
  filter(n_pairs > 2)
recent_HGT_pairs_raw.domain.data.to.plot.all.pident90$t_name = factor(recent_HGT_pairs_raw.domain.data.to.plot.all.pident90$t_name, levels = unique(recent_HGT_pairs_raw.domain.data.to.plot.all.pident90$t_name))
p=ggplot(recent_HGT_pairs_raw.domain.data.to.plot.all.pident90) + geom_col(aes(x = t_name, y = n_pairs, fill = h_name), col = "black") +
  theme_bw() +
  #facet_grid(stat~., scales = "free") +
    theme(axis.text.x = element_text(angle=45, hjust =1,vjust=1, size = text_size.x),
        axis.text.y = element_text(hjust = 1, size = text_size.y),
        legend.position = "left") +
  scale_y_sqrt(breaks = c(2,10,25,50,100,150)) +
  xlab("") +
  ylab("Num. protein pairs")
ggsave(sprintf("%sFigure_Supplementary/recent_HGT_domains_pident90_confirmed.jpg", OUTPUT.FIGURES.PATH), p, width = 15, height = 7)
```

```{r}
recent_HGT_pairs_70 = data.table::fread(sprintf("%sFigure_Supplementary/FigS11_recent_HGT/recent_HGT_network_70_confirmed.txt", OUTPUT.FIGURES.PATH)) %>%
  select(from, to, num.prot.pairs)
recent_HGT_pairs_90 = data.table::fread(sprintf("%sFigure_Supplementary/FigS11_recent_HGT/recent_HGT_network_90_confirmed.txt", OUTPUT.FIGURES.PATH)) %>%
  select(from, to, num.prot.pairs)

annotation.network.metadata = data.table::fread( 
                   sprintf("%sFigure_Supplementary/FigS2_annot_network/annotation.network.metadata.txt", OUTPUT.FIGURES.PATH)) %>%
  rbind(data.frame(node = 0, color = "#808080", size = 4, label = "unknown"))



pdf(sprintf("%sFigure_Supplementary/FigS11_recent_HGT//network_recent_HGT_igraph_70_confirmed.pdf", OUTPUT.FIGURES.PATH), width = 6, height = 12) #, units = "cm", res = 300)
par(mfrow=c(2,1))
VisualiseIgraphnetwork(data.for.network = recent_HGT_pairs_70 %>% mutate(weight = log10(num.prot.pairs)/3),
                      edge.colors = NULL,
                      node.color.map = annotation.network.metadata%>%
                                      select(node, color),
                      # node these sizes are defined at high threshold
                      node.size.map = annotation.network.metadata %>%
                                      select(node, size),
                      node.labels = annotation.network.metadata %>% 
                    select(node, label),
                      line.color.variable = "from",
                      line.color.legend.name = NULL,
                      font.size = 0.75,
                      vertex.size = 1,
                      main = "",
                      vertex.label.dist = 1,
                      include.labels = TRUE,
                      alpha = 0.3)
dev.off()


pdf(sprintf("%sFigure_Supplementary/FigS11_recent_HGT//network_recent_HGT_igraph_90_confirmed.pdf", OUTPUT.FIGURES.PATH), width = 6, height = 6) # units = "cm", res = 300)
VisualiseIgraphnetwork(data.for.network = recent_HGT_pairs_90 %>% mutate(weight = log10(num.prot.pairs)/3),
                      edge.colors = NULL,
                      node.color.map = annotation.network.metadata%>%
                                      select(node, color),
                      # node these sizes are defined at high threshold
                      node.size.map = annotation.network.metadata %>%
                                      select(node, size),
                      node.labels = annotation.network.metadata %>% 
                    select(node, label),
                      line.color.variable = "from",
                      line.color.legend.name = NULL,
                      font.size = 0.75,
                      vertex.size = 1,
                      main = "",
                      vertex.label.dist = 1,
                      include.labels = TRUE,
                      alpha = 0.3)
dev.off()

```

# look up the cases of recent mosaicism not confirmed by hhalign
```{r}
recent_HGT_pairs_raw.70.confirmed.stats = 
  data.frame(prop.confirmed.70 = sum(recent_HGT_pairs_raw.70.confirmed$mosaic.70),
             prop.confirmed.50 = sum(recent_HGT_pairs_raw.70.confirmed$mosaic.50))
recent_HGT_pairs_raw.70.confirmed.stats

recent_HGT_pairs_raw.90.confirmed.stats = 
  data.frame(prop.confirmed.70 = sum(recent_HGT_pairs_raw.90.confirmed$mosaic.70),
             prop.confirmed.90 = sum(recent_HGT_pairs_raw.90.confirmed$mosaic.90))
recent_HGT_pairs_raw.90.confirmed.stats

not.confirmed = recent_HGT_pairs_raw.90.confirmed %>% filter(!mosaic.70) %>% distinct(pair) %>%
  inner_join(recent.mosaicism.hhr)

not.confirmed.high.max.cov = not.confirmed %>% filter(max.cov > 0.80) %>% distinct(qname, sname)
not.confirmed.high.max.cov.qnames = unique(c(not.confirmed.high.max.cov$qname, not.confirmed.high.max.cov$sname))
#relaxely.annotated.proteins %>% filter(qname %in% not.confirmed.high.max.cov.qnames)

mid.annotated.proteins.including.multi.annot  %>% filter(qname %in% not.confirmed.high.max.cov.qnames)
surely.annotated.ecod.domains.high.confidence %>% filter(qname %in% not.confirmed.high.max.cov.qnames)
```
# find subdomain fragments
```{r}
recent_HGT_pairs_raw.domain.data.all.pident70 %>% filter(av.prop.domain.in.fragment < 0.6) %>% arrange(desc(av.prop.domain.in.fragment))
# look at second and third
selected.t.id = "3240.1.1"
selected.t.id = "4964.1.1"

ecod.domains.hits %>% filter(t_id == selected.t.id)
```

# Other ways of calculating mosaicism
```{r, eval = FALSE}
levels = c("mean.num.t", 
           "prop.mosaic.pairs.sequence.thr0p1",
           "prop.mosaic.pairs.sequence.thr0p3",
           "prop.mosaic.pairs.sequence.thr0p5", 
           "prob.mosaicism",
           "num.mosaic.pairs")

diversity.data.per.category = diversity.data.per.category %>% mutate(proportion = factor(proportion, levels = levels))
diversity.levels <- levels(diversity.data.per.category$proportion)
diversity.labeller <- character(length(diversity.levels))
diversity.labeller[diversity.levels == "mean.num.t"] <- "Mean number of folds\nper fold architecture"
diversity.labeller[diversity.levels == "prop.mosaic.pairs.sequence.thr0p1"] <- "Proportion of mosaic pairs\nby sequence (10%)"
diversity.labeller[diversity.levels == "prop.mosaic.pairs.sequence.thr0p3"] <- "Proportion of mosaic pairs\nby sequence (30%)"
diversity.labeller[diversity.levels == "prop.mosaic.pairs.sequence.thr0p5"] <- "Proportion of mosaic pairs\nby sequence (50%)"
diversity.labeller[diversity.levels == "prob.mosaicism"] <- "Prob. of domain mosaicism\nbetween fold architectures\nif sharing a fold"
diversity.labeller[diversity.levels == "num.mosaic.pairs"] <- "Number of pairs\nmosaic by domain"
#diversity.labeller[diversity.levels == "num.reprseq.pairs.domain"] <- "Number of protein pairs\nwith domain mosaicism"
#diversity.labeller[diversity.levels == "prop.mosaic"] <- "Prop. of proteins\nhaving any mosaic signal."
names(diversity.labeller) <- diversity.levels

p <- ggplot(diversity.data.per.category, aes(y = category, x = value, fill = category)) +
  geom_bar(stat = "identity", position=position_dodge()) +
  facet_grid(category ~ proportion, scales = "free", space = "free_y", 
                    labeller = labeller(category = phrog.class.labels, proportion = diversity.labeller)) +
  scale_fill_manual(values = PHROG.COLOR.MAP) + theme_minimal() + 
  theme(strip.text.y = element_text(face = "bold", size = 7, angle = 360)) + 
  labs(x = "", y = "") +
  scale_x_continuous(labels=function(x) sprintf("%.2f", x))

p.most.diverse <- p + guides(fill = "none")
p.most.diverse





Plot.Diversity.Data2 = function(diversity.data.per.category) {
  levels = c( "num.fold.types", 
              "num.fold.types.with.multi.x", 
              "num.theoretical.fold.type.pairs", 
              "num.theoretical.fold.type.pairs.with.multi.x",
              "num.pairs.sharing.t",
              "num.mosaic.pairs",
              "prop.pairs.mosaoc.by.domain")
  
  diversity.data.per.category = diversity.data.per.category %>% filter(proportion %in% levels) %>% mutate(proportion = factor(proportion, levels = levels))
  diversity.levels <- levels(diversity.data.per.category$proportion)
  diversity.labeller <- character(length(diversity.levels))
  diversity.labeller[diversity.levels == "num.fold.types"] <- "Num fold\narchitectures"
  diversity.labeller[diversity.levels == "num.fold.types.with.multi.x"] <- "Num folds\nwith multiple X"
  diversity.labeller[diversity.levels == "num.theoretical.fold.type.pairs"] <- "Num fold\ntype pairs"
  diversity.labeller[diversity.levels == "num.theoretical.fold.type.pairs.with.multi.x"] <- "Num pairs\nof fold types\n with multiple x"
  diversity.labeller[diversity.levels == "num.pairs.sharing.t"] <- "Num pairs sharing T"
  diversity.labeller[diversity.levels == "num.mosaic.pairs"] <- "Num mosaic pairs"
  diversity.labeller[diversity.levels == "prop.pairs.mosaoc.by.domain"] <- "Prop. of pairs\nmosaic by domain"
  #diversity.labeller[diversity.levels == "num.reprseq.pairs.domain"] <- "Number of protein pairs\nwith domain mosaicism"
  #diversity.labeller[diversity.levels == "prop.mosaic"] <- "Prop. of proteins\nhaving any mosaic signal."
  names(diversity.labeller) <- diversity.levels
  
  p <- ggplot(diversity.data.per.category, aes(y = annotation, x = value, fill = category)) +
    geom_bar(stat = "identity", position=position_dodge()) +
    facet_grid(category ~ proportion, scales = "free", space = "free_y", 
                      labeller = labeller(category = phrog.class.labels, proportion = diversity.labeller)) +
    scale_fill_manual(values = PHROG.COLOR.MAP) + theme_minimal() + 
    theme(strip.text.y = element_text(face = "bold", size = 7, angle = 360)) + 
    labs(x = "", y = "") +
    scale_x_continuous(labels=function(x) sprintf("%.2f", x))
  
  p.most.diverse <- p + guides(fill = "none")
  return(p.most.diverse)
}

p.most.diverse = Plot.Diversity.Data2(diversity.data.per.category %>% mutate(annotation = category))
p.most.diverse
ggsave(sprintf("%sFigure4/Figure4_per_category2.pdf", OUTPUT.FIGURES.PATH), p.most.diverse, width = 20, height = 5)


div.data.long = diversity.data  %>%
  select(category, annotation, mean.num.t, prop.mosaic.pairs.sequence.thr0p1, prop.mosaic.pairs.sequence.thr0p3, prop.mosaic.pairs.sequence.thr0p5, 
           prob.mosaicism, num.mosaic.pairs,
         num.fold.types, num.fold.types.with.multi.x, num.theoretical.fold.type.pairs, num.theoretical.fold.type.pairs.with.multi.x, prop.pairs.mosaoc.by.domain, num.pairs.sharing.t) %>%
  tidyr::gather(key = "proportion", value = "value", -category, -annotation)

p.most.diverse = Plot.Diversity.Data2(div.data.long)
p.most.diverse
ggsave(sprintf("%sFigure4/Figure4_2.pdf", OUTPUT.FIGURES.PATH), p.most.diverse, width = 20, height = 10)



```

```{r}
all.domain.network.metadata =   data.table::fread(sprintf("%sFigure5/all.domain.network.metadata.txt", OUTPUT.FIGURES.PATH)) 
all.domain.network = data.table::fread(sprintf("%sFigure5/all.domain.network.txt", OUTPUT.FIGURES.PATH))

  annotated.all.domain.network = Annotate_Graph(all.domain.network, 
                    edge.colors = NULL,
                    node.color.map = all.domain.network.metadata %>%
                                        select(node, color),
                    # node these sizes are defined at high threshold
                    node.size.map = all.domain.network.metadata %>%
                                        select(node, size),
                    node.labels = all.domain.network.metadata %>% 
                      select(node, label) %>%
                      rowwise() %>%
                      mutate(label = gsub(" ", "\n", label))%>%
                      mutate(label = if_else(label == "Intramolecular\nchaperone\ndomain\nin\nvirus\ntail\nspike\nprotein", "Intramolecular\nchaperone\ndomain in\nvirus tail\nspike protein", label)) ,
                    line.color.variable =  "from")
  
  annotated.domain.network.figure = VisualiseGGnetwork(annotated.all.domain.network, 
                     cex = 0.1, label_size = 1.5, layout = igraph::nicely(), main = "", 
                     nudge_y = 0, alpha = 1)
  annotated.domain.network.figure
  ggsave(annotated.domain.network.figure, filename = sprintf("%sFigure5/annotated.ALL.domain.network.figure.png", OUTPUT.FIGURES.PATH, selected_category), width = 28, height = 28)


```
