---
title: "generate_figures"
author: "Bogna Smug"
date: '2022-09-28'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(cowplot)
ecod_id_to_names_map = data.table::fread(sprintf("%secod_id_to_names_map.txt",OUTPUT.DATA.PATH)) %>% as.data.frame()
```

# 
```{r}
# PHROG CLASS LEGEND
dat = stack(PHROG.COLOR.MAP)
names(dat) = c("values", "Category")
ggp <- ggplot(dat, aes(x=values, y=values, fill = Category)) +    # Create ggplot2 plot
  geom_col(size = 5) +
  scale_fill_manual(values = PHROG.COLOR.MAP, name = "Category")

jpeg(sprintf("%sCategory_Legend.jpg", OUTPUT.FIGURES.PATH),  width = 10, height = 10, units = "cm", res = 300)
ggp_legend <- cowplot::get_legend(ggp) 
grid::grid.newpage()                                     # Draw empty plot window
grid::grid.draw(ggp_legend)  
dev.off()
```


# Fig 1
```{r}
col1.uniqueness <- "darkgreen"
col2.coverage <- "darkred"
point.size = 3
line.size = 1
text.size = 12
annotation.uncertainty.data.vs.cov = data.table::fread(sprintf("%sFigure1/Fig1_Tradeoff_cov.txt", OUTPUT.FIGURES.PATH)) %>% as.data.frame()
p.a=ggplot(data = annotation.uncertainty.data.vs.cov %>%
          mutate(`probability\nthreshold [%]` = as.factor(minimum.probability),
                  annotation.coverage = 100*annotation.coverage)) +
  geom_point(aes(x = annotation.coverage, y = perc.unique.annotation, linetype = `probability\nthreshold [%]`), col = col1.uniqueness, size = point.size) + 
  geom_line(aes(x = annotation.coverage, y = perc.unique.annotation, linetype = `probability\nthreshold [%]`), col = col1.uniqueness, size = line.size) + 
  geom_point(aes(x = annotation.coverage, y = perc.annotated, linetype = `probability\nthreshold [%]`), col = col2.coverage, size = point.size) + 
  geom_line(aes(x = annotation.coverage, y = perc.annotated, linetype = `probability\nthreshold [%]`), col = col2.coverage, size = line.size) + 
  Get.Theme(legend.position = "right") +
  xlab("sequence coverage threshold [%]") +
  theme( axis.title.y.right = element_text(colour = col2.coverage, size = text.size),
         axis.text.y.right = element_text(colour = col2.coverage, size = text.size),
          axis.title.y = element_text(colour = col1.uniqueness, size = text.size),
         axis.text.y = element_text(colour = col1.uniqueness, size = text.size),
           plot.title = element_text(size=14, face="bold", hjust = 0.5)) +
  scale_y_continuous(name = "functional uniqueness \n(% of annotated proteins with hits to a single function)",
                     limits = c(0,101),
                     breaks = seq(0,100,10),
                     sec.axis=sec_axis(~.*1,name="functional coverage \n(% proteins with a hit to any known function)"))  + 
  labs(title = "Impact of sequence coverage on functional annotation")


annotation.uncertainty.data.vs.prob = data.table::fread(sprintf("%sFigure1/Fig1_Tradeoff_prob.txt", OUTPUT.FIGURES.PATH))
p.b=ggplot(data = annotation.uncertainty.data.vs.prob %>%
             filter(annotation.coverage %in% c(0.1, 0.8)) %>%
          mutate(`sequence coverage\nthreshold [%]`  = as.factor(annotation.coverage*100))) +
  geom_point(aes(x = minimum.probability, y = perc.unique.annotation, linetype = `sequence coverage\nthreshold [%]` ), col = col1.uniqueness, size = point.size) + 
  geom_line(aes(x = minimum.probability, y = perc.unique.annotation, linetype = `sequence coverage\nthreshold [%]` ), col = col1.uniqueness, size = line.size) + 
  geom_point(aes(x = minimum.probability, y = perc.annotated, linetype = `sequence coverage\nthreshold [%]` ), col = col2.coverage, size = point.size) + 
  geom_line(aes(x = minimum.probability, y = perc.annotated, linetype = `sequence coverage\nthreshold [%]` ), col = col2.coverage, size = line.size) + 
  Get.Theme(legend.position = "right") +
  xlab("probability [%]") +
  theme( axis.title.y.right = element_text(colour = col2.coverage, size = text.size),
         axis.text.y.right = element_text(colour = col2.coverage, size = text.size),
          axis.title.y = element_text(colour = col1.uniqueness, size = text.size),
         axis.text.y = element_text(colour = col1.uniqueness, size = text.size),
           plot.title = element_text(size=14, face="bold", hjust = 0.5)) +
  scale_y_continuous(name = "functional uniqueness \n(% of annotated proteins with hits to a single function)",
                     limits = c(0,101),
                     breaks = seq(0,100,10),
                     sec.axis=sec_axis(~.*1,name="functional coverage \n(% proteins with a hit to any known function)")) + 
  labs(title = "Impact of hit probability on functional annotation")
```

```{r, eval = FALSE}
annotation.uncertainty.data.vs.eval = data.table::fread(sprintf("%sFigure1/Fig1_Tradeoff_eval.txt", OUTPUT.FIGURES.PATH))
p.c=ggplot(data = annotation.uncertainty.data.vs.eval %>%
          mutate(`sequence coverage\nthreshold [%]`  = as.factor(annotation.coverage*100))) +
  geom_point(aes(x = maximum.eval, y = perc.unique.annotation, linetype = `sequence coverage\nthreshold [%]` ), col = col1.uniqueness, size = point.size) + 
  geom_line(aes(x = maximum.eval, y = perc.unique.annotation, linetype = `sequence coverage\nthreshold [%]` ), col = col1.uniqueness, size = line.size) + 
  geom_point(aes(x = maximum.eval, y = perc.annotated, linetype = `sequence coverage\nthreshold [%]` ), col = col2.coverage, size = point.size) + 
  geom_line(aes(x = maximum.eval, y = perc.annotated, linetype = `sequence coverage\nthreshold [%]` ), col = col2.coverage, size = line.size) + 
  Get.Theme(legend.position = "right") +
  xlab("e-value") +
  theme( axis.title.y.right = element_text(colour = col2.coverage),
         axis.text.y.right = element_text(colour = col2.coverage),
          axis.title.y = element_text(colour = col1.uniqueness),
         axis.text.y = element_text(colour = col1.uniqueness),
           plot.title = element_text(size=14, face="bold", hjust = 0.5)) +
  scale_y_continuous(name = "functional uniqueness \n(% of annotated proteins with hits to a single function)",
                     limits = c(0,101),
                     breaks = seq(0,100,10),
                     sec.axis=sec_axis(~.*1,name="functional coverage \n(% proteins with a hit to any known function)")) +
  scale_x_log10() + 
  labs(title = "Impact of hit e-value on functional annotation")

```

```{r, eval = TRUE}
p.figure <- plot_grid(p.a, p.b, labels = c("A", "B"), label_size = 25, ncol = 1)
ggsave(p.figure, filename = sprintf("%sFigure1/Supplementary_Figure1.png", OUTPUT.FIGURES.PATH), width = 12, height = 10)
```


# Domain  network
```{r}
domain.network.metadata =   data.table::fread(sprintf("%sFigure5/domain.network.metadata.txt", OUTPUT.FIGURES.PATH))
nucl.metabolism.domain.network = data.table::fread(sprintf("%sFigure5/nucl.metabolism.domain.network.txt", OUTPUT.FIGURES.PATH))

for (selected_category in unique(domain.network.metadata$category)) {
  annotated.domain.network = Annotate_Graph(nucl.metabolism.domain.network %>% filter(category == selected_category), 
                    edge.colors = NULL,
                    node.color.map = domain.network.metadata %>%
                      filter(category == selected_category) %>%
                                        select(node, color),
                    # node these sizes are defined at high threshold
                    node.size.map = domain.network.metadata %>%
                      filter(category == selected_category) %>%
                                        select(node, size),
                    node.labels = domain.network.metadata %>% 
                      filter(category == selected_category) %>%
                      select(node, label) %>%
                      rowwise() %>%
                      mutate(label = gsub(" ", "\n", label)),
                    line.color.variable =  "from")
  
  annotated.domain.network.figure = VisualiseGGnetwork(annotated.domain.network, 
                     cex = 0.1, label_size = 1.5, layout = igraph::nicely(), main = "", 
                     nudge_y = 0, alpha = 0.3)
  annotated.domain.network.figure
  ggsave(annotated.domain.network.figure, filename = sprintf("%sFigure5/annotated.domain.network.figure_%s.png", OUTPUT.FIGURES.PATH, selected_category), width = 8, height = 8)
}


```


```{r}

annotation.netwok.relaxed.threshold = data.table::fread( 
                   sprintf("%sFigure1/annotation.netwok.relaxed.threshold.txt", OUTPUT.FIGURES.PATH))
annotation.netwok.default.threshold = data.table::fread( 
                   sprintf("%sFigure1/annotation.netwok.default.threshold.txt", OUTPUT.FIGURES.PATH))
annotation.network.metadata = data.table::fread( 
                   sprintf("%sFigure1/annotation.network.metadata.txt", OUTPUT.FIGURES.PATH)) %>%
  rowwise() %>%
  mutate(label = if_else(label == "DNA\npolymerase/primase", "DNA\npolymerase/\nprimase",  gsub("\n", " ", label)))

  
annotated.annotation.network.relaxed.threshold = Annotate_Graph(annotation.netwok.relaxed.threshold, 
                  edge.colors = NULL,
                  node.color.map = annotation.network.metadata%>%
                                      select(node, color),
                  # node these sizes are defined at high threshold
                  node.size.map = annotation.network.metadata %>%
                                      select(node, size),
                  node.labels = annotation.network.metadata %>% 
                    select(node, label),
                  line.color.variable =  "from")
annotated.annotation.network.default.threshold = Annotate_Graph(annotation.netwok.default.threshold, 
                  edge.colors = NULL,
                  node.color.map = annotation.network.metadata%>%
                                      select(node, color),
                  # node these sizes are defined at high threshold
                  node.size.map = annotation.network.metadata %>%
                                      select(node, size),
                  node.labels = annotation.network.metadata %>% 
                    select(node, label),
                  line.color.variable =  "from")



network.relaxed.figure = VisualiseGGnetwork(annotated.annotation.network.relaxed.threshold, 
                   cex = 0.1, label_size = 2.35, layout = igraph::nicely(), main = "", nudge_y = 0.005, alpha = 0.3) #nudge_y = 0.015,
network.relaxed.figure
ggsave(network.relaxed.figure, filename = sprintf("%sFigure1/Relaxed_network.png", OUTPUT.FIGURES.PATH), width = 9, height = 10)

network.default.figure = VisualiseGGnetwork(annotated.annotation.network.default.threshold, 
                   cex = 0.1, label_size = 2.5, layout = igraph::nicely(), main = "", nudge_y = 0.04, alpha = 0.5)
network.default.figure
ggsave(network.default.figure, filename = sprintf("%sFigure1/Default_network.png", OUTPUT.FIGURES.PATH), width = 5, height = 5)

```

```{r}
recent_HGT_pairs = data.table::fread(sprintf("%sFigure5/recent_HGT_network.txt", OUTPUT.FIGURES.PATH)) %>%
  select(from, to, num.prot.pairs)



annotation.network.metadata = data.table::fread( 
                   sprintf("%sFigure1/annotation.network.metadata.txt", OUTPUT.FIGURES.PATH)) %>%
  rbind(data.frame(node = 0, color = "#808080", size = 4, label = "unknown"))

  
annotated.recent_HGT_pairs = Annotate_Graph(recent_HGT_pairs, 
                  edge.colors = NULL,
                  node.color.map = annotation.network.metadata%>%
                                      select(node, color),
                  # node these sizes are defined at high threshold
                  node.size.map = annotation.network.metadata %>%
                                      select(node, size),
                  node.labels = annotation.network.metadata %>% 
                    select(node, label),
                  line.color.variable =  "from")

network.recent.HGT = VisualiseGGnetwork(annotated.recent_HGT_pairs, 
                   cex = 0.1, 
                   label_size = 1.5, 
                   layout = igraph::nicely(), 
                   main = "", 
                   nudge_y = 0.04, 
                   alpha = 0.5, 
                   remove.loops  = F)
network.recent.HGT
ggsave(network.recent.HGT, filename = sprintf("%sFigure5/network_recent_HGT.jpg", OUTPUT.FIGURES.PATH), width = 5, height = 5)


jpeg(filename = sprintf("%sFigure5/network_recent_HGT_igraph.jpg", OUTPUT.FIGURES.PATH), width = 15, height = 15, units = "cm", res = 300)
VisualiseIgraphnetwork(data.for.network = recent_HGT_pairs %>% mutate(weight = log10(num.prot.pairs)/3),
                      edge.colors = NULL,
                      node.color.map = annotation.network.metadata%>%
                                      select(node, color),
                      # node these sizes are defined at high threshold
                      node.size.map = annotation.network.metadata %>%
                                      select(node, size),
                      node.labels = annotation.network.metadata %>% 
                    select(node, label),
                      line.color.variable = "from",
                      line.color.legend.name = NULL,
                      font.size = 0.75,
                      vertex.size = 1,
                      main = "",
                      vertex.label.dist = 1,
                      include.labels = TRUE,
                      alpha = 0.3)
dev.off()

```

# Fig 3 network
```{r}
mosaic.network = data.table::fread(sprintf("%sFigure3/3a_mosaic.network.txt", OUTPUT.FIGURES.PATH))
#mosaic.metadata = data.table::fread(sprintf("%sFigure3/3a_mosaic.metadata.txt", OUTPUT.FIGURES.PATH), sep = "\t")



jpeg(filename = sprintf("%sFigure3/network.jpg", OUTPUT.FIGURES.PATH), width = 10, height = 10, units = "cm", res = 300)
VisualiseIgraphnetwork(data.for.network = mosaic.network %>% mutate(weight = log10(num.reprseq.any.mossaic)/20) %>% 
                         select(from = from.index, to = to.index, weight, dataset),
                      edge.colors = data.frame(value = c("ecod", "seq", "both"), color = c("gray", "gray", "darkred")),
                      edge.linetypes = data.frame(value = c("ecod", "seq", "both"), lty = c("solid", "dotted", "solid")),
                      node.color.map = annotation.network.metadata%>%
                                      select(node, color),
                      # node these sizes are defined at high threshold
                      node.size.map = annotation.network.metadata %>%
                                      select(node, size) %>% mutate(size = 2*size),
                      node.labels = annotation.network.metadata %>% 
                    select(node, label),
                      line.color.variable = "dataset",
                      line.color.legend.name = "Mosaicism via",
                      font.size = 0.25,
                      main = "",
                      vertex.label.dist = 1,
                      include.labels = TRUE,
                      alpha = 1,
                    label.font = 2,
                    legend.title = "Mosaicism via:",
                    node.label.color = "black")
dev.off()
```


```{r}
p.figure <- plot_grid(network.default.figure, network.relaxed.figure, labels = c("A", "B"), label_size = 25, ncol = 1, rel_heights = c(0.27, 0.73))
ggsave(p.figure, filename = sprintf("%sFigure1/Supplementary_Figure2.pdf", OUTPUT.FIGURES.PATH), width =8, height = 12)
ggsave(p.b, filename = sprintf("%sFigure1/Suppl_Figure1b.png", OUTPUT.FIGURES.PATH), width = 10, height = 5)
ggsave(network.default.figure, filename = sprintf("%sFigure1/Suppl_Figure1_network.default.figure.png", OUTPUT.FIGURES.PATH), width = 5, height = 5)
```


# Fig 2: heatmap of ECODS found in multiple categories
```{r}

text_size.x = 9
text_size.y = 9

h.domain.occurence.data = data.table::fread(sprintf("%sFigure2/H_domains.txt", OUTPUT.FIGURES.PATH)) %>% 
  as.data.frame() 
h.domain.occurence.data$category <- factor(h.domain.occurence.data$category, levels = phrogs.class.order)

phrog.class.labels2 = phrog.class.labels
phrog.class.labels2[which(names(phrog.class.labels2) == "head and packaging")] = "head\nand\npack."
phrog.class.labels2[which(names(phrog.class.labels2) == "DNA, RNA and nucleotide metabolism")] = "DNA, RNA\nand\nnucleotide\nmetabolism"
ggplot(h.domain.occurence.data) +
  geom_tile(aes(x=h_name, y = annotation, fill = category)) + #, hjust = 0, vjust = 0
  theme(axis.text.x = element_text(angle=45, hjust =1,vjust=1, size = text_size.x),
        axis.text.y = element_text(hjust = 1,vjust=0.5, size = text_size.y),
        strip.text.y = element_text(face = "bold", size = 6, angle = 360),
        strip.text.x = element_text(face = "bold", size = 6, angle = 360)) +
  facet_grid(category ~all.categories, scales = "free", space = "free", 
             labeller = labeller(category = phrog.class.labels,
                                 all.categories = c(phrog.class.labels2, "multiple categories" = "multiple\ncategories"))) + 
  xlab("") + ylab("") +
  guides(fill = "none") +
  scale_fill_manual(values = PHROG.COLOR.MAP)

ggsave(sprintf("%sFigure2/H_domains.jpg", OUTPUT.FIGURES.PATH), width = 9, height = 10)


num.f.within.h = data.table::fread(sprintf("%sFigure2/num.f.within.h.txt", OUTPUT.FIGURES.PATH)) 

num.f.within.h.bars = num.f.within.h %>%
  filter(in.ecod.heatmap) %>%
  rename(family = num_f, topology = num_t) %>%
  tidyr::gather(key = "ECOD level", value = "num.groups", family, topology)

ggplot(num.f.within.h.bars) +
  geom_col(aes(x = h_name, y = num.groups, fill = all.categories, alpha = `ECOD level`), position = position_dodge2(preserve = "single")) +
    theme(axis.text.x = element_text(angle=45, hjust =1,vjust=1, size = text_size.x),
        axis.text.y = element_text(hjust = 1,vjust=0.5, size = text_size.y),
        strip.text.y = element_text(face = "bold", size = 6, angle = 360),
        strip.text.x = element_text(face = "bold", size = 6, angle = 360)) +
  facet_grid(. ~all.categories, scales = "free", space = "free", 
             labeller = labeller(all.categories = c(phrog.class.labels2, "multiple categories" = "multiple\ncategories"))) + 
  xlab("") + ylab("Num. of domain families in the group.") +
  guides(fill = "none") +
  scale_fill_manual(values = c(PHROG.COLOR.MAP, "multiple categories" = "#000000")) +
  scale_y_sqrt(breaks = c(1,10,25,50,100,150)) +
  scale_alpha_manual(values = c("family" = 0.5, "topology" =1))
ggsave(sprintf("%sFigure2/num.f.within.h.jpg", OUTPUT.FIGURES.PATH), width = 10, height = 7)


ggplot(num.f.within.h) +
  geom_point(aes(x = num_prot, y = num_f)) +
  scale_x_log10() +
  scale_y_log10()
cor.test(num.f.within.h$num_f, num.f.within.h$num_prot, method = "spearman")

t.domain.occurence.data.full = data.table::fread(sprintf("%sFigure2/T_domains.txt", OUTPUT.FIGURES.PATH)) %>%
  as.data.frame() 
t.domain.occurence.data.full$category <- factor(t.domain.occurence.data.full$category, levels = phrogs.class.order)
ggplot(t.domain.occurence.data.full) +
  geom_tile(aes(y=t_name, x = annotation, fill = category)) + #, hjust = 0, vjust = 0
  theme(axis.text.x = element_text(angle=45, hjust =1,vjust=1, size = text_size.x),
        axis.text.y = element_text(hjust = 1,vjust=0.5, size = text_size.y),
        strip.text.y = element_text(face = "bold", size = 6, angle = 360),
        strip.text.x = element_text(face = "bold", size = 6, angle = 360)) +
  facet_grid(all.categories ~category, scales = "free", space = "free", 
             labeller = labeller(category = phrog.class.labels,
                                 all.categories = c(phrog.class.labels2, "multiple categories" = "multiple\ncategories"))) + 
  xlab("") + ylab("") +
  guides(fill = "none") +
  scale_fill_manual(values = PHROG.COLOR.MAP)
ggsave(sprintf("%sFigure2/T_domains.jpg", OUTPUT.FIGURES.PATH), width = 20, height = 20)


```






```{r}
library(RColorBrewer)
text.size.axis = 6
text.size.panel = 12
most.mosaic.classes = c("tail fiber", "endolysin", "DNA polymerase", "major tail")


  domain.position.plots = list()
  tile.data = data.table::fread(sprintf("%sFigure5/domain.positions.txt", OUTPUT.FIGURES.PATH)) %>%
    filter(domain.level == "T" & annotation %in% most.mosaic.classes) %>%
              # keep only the ones with multidomain
    group_by(qname) %>%
    mutate(num.domains = n_distinct(domain[domain != "undetected"])) %>%
    ungroup() %>%
    filter(num.domains > 1)

  
  
        
      for (this.annotation in unique(tile.data$annotation)) {
        this.tile.data = tile.data %>% 
          filter(annotation == this.annotation)  %>% 
          mutate(annotation = this.annotation) %>%
          arrange(row) %>%
          mutate(domain = domain_name) %>%
          group_by(qname) %>%
          arrange(pos.start, pos.end) %>% 
          mutate(domain.combination = paste(unique(domain), collapse = " | ", sep = "")) %>%
          ungroup() %>%
          arrange(qname) %>%
          # select only one qname per domain combination
          group_by(domain.combination) %>%
          arrange(pos.start) %>%
          mutate(qname1 = qname[1]) %>%
          ungroup() %>%
          filter(qname == qname1) %>%
          rowwise() %>%
          mutate(domain_new = if_else(
            domain_name == "undetected" | domain_name == "multiple domains",
            domain_name,
            #paste(domain_name, " (X: ", x_name, " [nr  ",x.index ,"]", ")", collapse = "", sep = ""))) %>%
            paste(x.index, ": ", domain_name, collapse = "", sep = ""))) %>%
          ungroup() #%>%
          #rowwise() %>%
          #mutate(domain_new = gsub(" ", "\n", domain_new))
        
        
        # create a color pallete where domains from common X are different shades of the same color
        this.x = this.tile.data %>% filter(!(domain %in% c("undetected", 
                                                           "multiple domains"))) %>% distinct(x.index) %>% pull(x.index)
        #x.colors = randomcoloR::distinctColorPalette(length(this.x))
        x.colors = mycolors <- colorRampPalette(brewer.pal(8, "Dark2"))(length(this.x))
        x.colors = data.frame(x.index = this.x, color = x.colors)
        all.colors = data.frame(domain = character(0), color = character(0))
        for (this.x.index in this.x) {
          all.domains = this.tile.data %>% filter(x.index == this.x.index) %>% distinct(domain_new) %>% 
            pull(domain_new)
          this.color = x.colors %>% filter(x.index == this.x.index) %>% pull(color)
          this.x.colors.pallete =  colorRampPalette(this.color)
          this.colors = this.x.colors.pallete(length(all.domains))
          all.colors = rbind(all.colors, data.frame(domain = all.domains, color = this.colors))
          print(length(all.domains))
        }
                
        all.colors = rbind(all.colors, data.frame(domain = c("undetected", "multiple domains"), 
                                                  color = c( "#FFFFFF",  "#000000"), stringsAsFactors = FALSE))

        colm = all.colors$color
        names(colm) = all.colors$domain

        
        this.tile.data.row.numbers = this.tile.data %>%
          arrange(domain.combination, qname) %>%
          distinct(domain.combination, qname) %>%
          mutate(dummy = 1) %>%
          group_by(dummy) %>%
          mutate(row.plus = 1:n()) %>%
          mutate(row = row.plus - 0.5)
        
        this.tile.data = this.tile.data %>%
          select(-row, -row.plus) %>%
          left_join(this.tile.data.row.numbers)
        
        gg_rect = Show.Domain.Position.Within.Data(
          tile.data = this.tile.data %>% select(-domain) %>% rename(domain = domain_new),
          colormap = colm, 
          my.theme = theme.no.verical, 
          color.frames = FALSE) +
          #scale_y_discrete(breaks =this.tile.data$qname, labels = this.tile.data$family) +
          
            theme(strip.text.x = element_text(size = text.size.panel), 
            #legend.box="vertical", legend.margin=margin(),
                axis.title.x = element_text(size = text.size.axis),
                axis.title.y = element_text(size = text.size.axis),
                #axis.text.x = element_blank(),
                #axis.text.y = element_blank(),
                axis.text.y = element_text(size = text.size.axis)
                #axis.ticks.x = element_blank(),
                #axis.ticks.y = element_blank()
                ) 
                
        domain.position.plots[[this.annotation]] =  gg_rect
  }
  

  
      
      
library(gridExtra)
          pdf(sprintf("%sFigure5/domain.positions_most_mosaic.pdf", OUTPUT.FIGURES.PATH), 
         width = 15,
         height = 25)
do.call("grid.arrange", c(domain.position.plots, ncol=1))
dev.off()
```




# Fig5: SHINY PLOTS
```{r}
text.size.axis = 6
text.size.panel = 12

  domain.position.plots = list()
  tile.data = data.table::fread(sprintf("%sFigure5/domain.positions.txt", OUTPUT.FIGURES.PATH)) %>% filter(domain.level == "T")

  colormap = tile.data %>% distinct(domain) %>% filter(!(domain %in% c("undetected", "multiple domains")))
  colormap$color = randomcoloR::distinctColorPalette(nrow(colormap))
  colormap = rbind(colormap, data.frame(domain = c("undetected", "multiple domains"), 
                                                  color = c( "#FFFFFF",  "#000000"), stringsAsFactors = FALSE))
  colm = colormap$color
  names(colm) = colormap$domain
        
      for (this.annotation in unique(tile.data$annotation)) {
        this.tile.data = tile.data %>% 
          filter(annotation == this.annotation)  %>% 
          mutate(annotation = this.annotation) %>%
          arrange(row)
        
        gg_rect = Show.Domain.Position.Within.Data(
          this.tile.data,
          colm, 
          theme.no.verical) +
          #scale_y_discrete(breaks =this.tile.data$qname, labels = this.tile.data$family) +
          
            theme(strip.text.x = element_text(size = text.size.panel), 
            legend.position = "none") +
              theme(
                axis.title.x = element_text(size = text.size.axis),
                axis.title.y = element_text(size = text.size.axis),
                #axis.text.x = element_blank(),
                axis.text.y = element_blank(),
                #axis.text.y = element_text(size = text.size.axis),
                #axis.ticks.x = element_blank(),
                axis.ticks.y = element_blank())
                
        domain.position.plots[[this.annotation]] =  gg_rect
  }
  
  
  #Create a subfigure with legend only, take only the most frequent
  colormap.with.names = colormap %>% inner_join(tile.data %>% 
                                                 group_by(domain_name) %>%
                                                 mutate(num_qnames = n_distinct(qname)) %>%
                                                 filter(num_qnames >= 3) %>%
                                                 distinct(domain, domain_name)) %>% distinct(color, domain_name)
  colm.with.names = colormap.with.names$color
  names(colm.with.names) = colormap.with.names$domain_name
  
  g.dummy = ggplot(tile.data, aes(x=qname, y = domain, fill = domain_name)) + geom_col() + 
    scale_fill_manual(values = colm.with.names, name = 'Domain topology') +
    theme(legend.margin =margin(r=0,l=0,t=0,b=0), text = element_text(size = 7)) +
    guides(fill=guide_legend(ncol=6))
  
  leg <- ggpubr::get_legend(g.dummy, position = "right")
  ggleg = ggpubr::as_ggplot(leg)
#grid::widthDetails(leg)
#grid::heightDetails(leg)


  
    ncol = ceiling(length(domain.position.plots)/4)
    jpeg(sprintf("%sFigure5/domain.positions.jpg", OUTPUT.FIGURES.PATH), 
         width = 50, 
         height = 30, units = "cm", res = 300)
    
    ggpubr::ggarrange(
      egg::ggarrange(plots = domain.position.plots,
                     ncol = ncol, nrow = 4),
      ggleg,
      nrow = 2,
      heights = c(0.77,0.25))
      #legend.prob = ggleg,
      #nrow = 1,
      #legend = "bottom")
  dev.off()
  
    pdf(sprintf("%sFigure5/domain.positions_top.pdf", OUTPUT.FIGURES.PATH), 
         width = 10, 
         height = 10)
      egg::ggarrange(plots = domain.position.plots,
                     ncol = ncol, nrow = 4)
      dev.off()
      
      
    pdf(sprintf("%sFigure5/domain.positions_bottom.pdf", OUTPUT.FIGURES.PATH), 
         width = 20, 
         height = 10)
    ggleg
      dev.off()
```

# Fig. 4: diversity
```{r}
diversity = data.table::fread(sprintf("%sFigure4/Diversity_vs_mosaicism.txt", OUTPUT.FIGURES.PATH))


Fig4a = ggplot(diversity, aes(x=prop.proteins.with.ecod.hit)) + 
  geom_histogram(fill = "blue", position="dodge", bins = 20, color = "black") + 
  theme_minimal() + 
  labs(x = "Proportion of proteins with ECOD hit",
       y = "Number of functional classes")


# label the ones that have many families or fold types

diversity.ok.ecod = diversity %>% filter(!poorly.ecod.annotated)  %>%
  mutate(label = if_else(diverse.for.label,annotation , ""))


Fig4b = ggplot(diversity.ok.ecod) + 
  #geom_point(aes(x = num.proteins, y = num.topology.combinations, colour = category)) + 
  #geom_vline(aes(xintercept = median.num.prot), col = "red", linetype = "dashed") +
  geom_point(aes(x = num.families, y = num.topology.combinations, colour = category)) + 
  geom_vline(aes(xintercept = median.num.fam), col = "red", linetype = "dashed") +
  geom_hline(aes(yintercept = median.num.topology.combinations), col = "red", linetype = "dashed") +
  scale_x_log10() + 
  #ggrepel::geom_label_repel(aes(x = num.proteins, y = num.topology.combinations, colour = category, label = label), size = 3) + 
  ggrepel::geom_label_repel(aes(x = num.families, y = num.topology.combinations, colour = category, label = label), size = 3) + 
  scale_colour_manual(values = PHROG.COLOR.MAP) + 
  labs(x = "Number of families", y = "Number of fold combinations") + 
  guides(colour = "none") + theme_minimal()

p.panelab <- plot_grid(Fig4a, Fig4b, labels = c("A", "B"), label_size = 8, ncol = 2, rel_widths  = c(1,2))
p.panelab

# Fig 4c
# plot the relation between genetic and structural diversity

levels = c("mean.num.t", 
           "prop.mosaic.pairs.sequence.thr0p1",
           "prop.mosaic.pairs.sequence.thr0p3",
           "prop.mosaic.pairs.sequence.thr0p5", 
           "prob.mosaicism",
           "num.mosaic.pairs")
diversity.top = data.table::fread(sprintf("%sFigure4/mosaicism.top.diverse.classes.txt", OUTPUT.FIGURES.PATH)) %>%
  filter(proportion %in% levels)
diversity.top = diversity.top %>% mutate(proportion = factor(proportion, levels = levels))
diversity.levels <- levels(diversity.top$proportion)
diversity.labeller <- character(length(diversity.levels))
diversity.labeller[diversity.levels == "mean.num.t"] <- "Mean number of folds\nper fold architecture"
diversity.labeller[diversity.levels == "prop.mosaic.pairs.sequence.thr0p1"] <- "Proportion of mosaic pairs\nby sequence (10%)"
diversity.labeller[diversity.levels == "prop.mosaic.pairs.sequence.thr0p3"] <- "Proportion of mosaic pairs\nby sequence (30%)"
diversity.labeller[diversity.levels == "prop.mosaic.pairs.sequence.thr0p5"] <- "Proportion of mosaic pairs\nby sequence (50%)"
diversity.labeller[diversity.levels == "prob.mosaicism"] <- "Prob. of domain mosaicism\nbetween fold architectures\nif sharing a fold"
diversity.labeller[diversity.levels == "num.mosaic.pairs"] <- "Number of pairs\nmosaic by domain"
#diversity.labeller[diversity.levels == "num.reprseq.pairs.domain"] <- "Number of protein pairs\nwith domain mosaicism"
#diversity.labeller[diversity.levels == "prop.mosaic"] <- "Prop. of proteins\nhaving any mosaic signal."
names(diversity.labeller) <- diversity.levels

p <- ggplot(diversity.top, aes(y = annotation, x = value, fill = category)) +
  geom_bar(stat = "identity", position=position_dodge()) +
  facet_grid(category ~ proportion, scales = "free", space = "free_y", 
                    labeller = labeller(category = phrog.class.labels, proportion = diversity.labeller)) +
  scale_fill_manual(values = PHROG.COLOR.MAP) + theme_minimal() + 
  theme(strip.text.y = element_text(face = "bold", size = 7, angle = 360)) + 
  labs(x = "", y = "") +
  scale_x_continuous(labels=function(x) sprintf("%.2f", x))

p.most.diverse <- p + guides(fill = "none")
p.most.diverse

p.fig4 <- plot_grid(p.panelab, p.most.diverse, ncol = 1, labels = c("", "C"), label_size = 8, rel_heights = c(0.4, 0.6))
p.fig4.filename <- sprintf("%sFigure4/Figure4.png", OUTPUT.FIGURES.PATH)
ggsave(p.fig4.filename, p.fig4, width = 12, height = 10)
ggsave(sprintf("%sFigure4/Figure4.pdf", OUTPUT.FIGURES.PATH), p.fig4, width = 12, height = 10)

## supplementary version
# Fig 4c
# plot the relation between genetic and structural diversity

levels.supp = c("mean.num.t.per.prot", 
           "prob.mosaicism.if.sharing.fold.and.multi.x.family.measure")
diversity.top.supp = data.table::fread(sprintf("%sFigure4/mosaicism.top.diverse.classes.txt", OUTPUT.FIGURES.PATH)) %>%
  filter(proportion %in% levels.supp)
diversity.top.supp = diversity.top.supp %>% mutate(proportion = factor(proportion, levels = levels.supp))
diversity.levels.supp <- levels(diversity.top.supp$proportion)
diversity.labeller <- character(length(diversity.levels.supp))
diversity.labeller[diversity.levels.supp == "mean.num.t.per.prot"] <- "Mean number of folds\nper protein family"
diversity.labeller[diversity.levels.supp == "prob.mosaicism.if.sharing.fold.and.multi.x.family.measure"] <- "Probability of domain mosaicism\nbetween protein families \nif sharing a fold \nand having multiple X domains"

names(diversity.labeller) <- diversity.levels.supp

p <- ggplot(diversity.top.supp, aes(y = annotation, x = value, fill = category)) +
  geom_bar(stat = "identity", position=position_dodge()) +
  facet_grid(category ~ proportion, scales = "free", space = "free_y", 
                    labeller = labeller(category = phrog.class.labels, proportion = diversity.labeller)) +
  scale_fill_manual(values = PHROG.COLOR.MAP) + theme_minimal() + 
  theme(strip.text.y = element_text(face = "bold", size = 7, angle = 360)) + 
  labs(x = "", y = "")
p.most.diverse.supp <- p + guides(fill = "none")
p.most.diverse.supp

p.fig4.filename <- sprintf("%sFigure4/Figure4c_supplementary_version.png", OUTPUT.FIGURES.PATH)
ggsave(p.fig4.filename, p.most.diverse.supp, width = 15, height = 8)


```

Poorly annotated ECOD analysis
```{r}
classes.with.few.ecod.annotated.prots.new = data.table::fread(sprintf("%sFigure_Supplementary/classes.with.few.ecod.annotated.txt", OUTPUT.FIGURES.PATH))
classes.with.few.ecod.annotated.prots.new$annotation = factor(classes.with.few.ecod.annotated.prots.new$annotation , levels = unique(classes.with.few.ecod.annotated.prots.new$annotation))
classes.with.few.ecod.annotated.prots.long = classes.with.few.ecod.annotated.prots.new %>% 
  select(annotation, category, `prot. with any ECOD hit`,  `proteome covered by ECOD hits`) %>%
  tidyr::gather(key = "stat", value = "prop",`prot. with any ECOD hit`,  `proteome covered by ECOD hits`)

p=ggplot(classes.with.few.ecod.annotated.prots.long, aes(x = annotation, y = prop, fill = category, alpha = stat)) +
   geom_bar(stat = "identity", position=position_dodge()) +
  facet_grid(. ~ category, scales = "free_x", space = "free_x") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 1 )) +
  scale_y_continuous(limits = c(0,1))+ 
  guides(fill = "none")+ 
  labs(x = " function", y = "Proportion") +
  scale_fill_manual(values = PHROG.COLOR.MAP) +
  scale_alpha_discrete(range = c(1, .4))
p


ggsave(sprintf("%sFigure_Supplementary/poor_ecod_annotation.png", OUTPUT.FIGURES.PATH), p,width = 20, height = 10)

```



# Fig 3d NEW
```{r}
table.unknown.seq.functions = data.table::fread(sprintf("%sFigure3/table.seq.functions.low.cov.txt", OUTPUT.FIGURES.PATH))
table.unknown.seq.functions = table.unknown.seq.functions %>%
  filter(annotation != "unknown") %>%
  group_by(mosaic) %>%
  mutate(total.weight = sum(weight)) %>%
  ungroup() %>%
  mutate(freq = weight/total.weight) 

included.annots = table.unknown.seq.functions %>%
  #filter(weight >= 50) %>%
  filter(freq > 0.015) %>%
  distinct(annotation)

table.unknown.seq.functions = table.unknown.seq.functions %>%
  inner_join(included.annots) %>%
  group_by(annotation) %>%
  mutate(sum.weight = sum(weight)) %>%
  arrange(sum.weight)

table.unknown.seq.functions$category[table.unknown.seq.functions$category == "unknown"] <- "other"
table.unknown.seq.functions$annotation <- factor(table.unknown.seq.functions$annotation, 
                                                 levels = unique(table.unknown.seq.functions %>% pull(annotation) %>% unique()))

  
functions.low.cov=ggplot(data=table.unknown.seq.functions, aes(x=annotation, y=freq, fill=category, alpha = mosaic)) + 
  geom_bar(stat="identity", position = position_dodge2(width = 0.8, preserve = "single"), col = "black") + 
  scale_fill_manual(values = PHROG.COLOR.MAP) +
  #scale_color_manual(values = PHROG.COLOR.MAP) +
  guides(col = "none") +
  scale_alpha_manual(values = c("Mosaic" = 1, "Not mosaic" = 0.4)) +
  #facet_grid(.~mosaic) +
  theme_minimal() + 
  guides(fill = "none", color = "none") + 
  theme(legend.text=element_text(size=4)) + 
  labs(x = "", y = "frequency of weighted occurrence", fill = "category") + 
  coord_flip() 
functions.low.cov
ggsave(filename = sprintf("%sFigure3/low.cov.funct.all.proteins_old.jpg", OUTPUT.FIGURES.PATH) , functions.low.cov, width = 15, height = 6)
```

```{r, fig.height =5, fig.width =10}
annot.stats.per.category.and.mosaicism = data.table::fread(file = sprintf("%sFigure3/unknown_functions_mosaic_vs_nonmosaic.txt", OUTPUT.FIGURES.PATH)) %>%
  arrange(category, annotation)


p.annot.low.cov = ggplot(annot.stats.per.category.and.mosaicism %>%
                           filter(!is.na(category) & category != "") %>%
  mutate(mosaic = if_else(mosaic, "Mosaic", "Not mosaic")) %>% as.data.frame()) +
  geom_col(aes(x=annotation, y = prop.proteins.has.this.annot, fill = category, alpha = mosaic), position = position_dodge2(preserve = "single") ) +
  facet_grid(.~category, scales = "free", space = "free_x", labeller = labeller(category = phrog.class.labels)) +
  scale_alpha_manual(values = c("Mosaic" = 1, "Not mosaic" = 0.4)) +
  scale_fill_manual(values = PHROG.COLOR.MAP) +
  theme(axis.text.x = element_text(angle=45, size = 8, vjust = 1, hjust = 1),
        axis.text.y = element_text(size = 9)) +
  guides(fill = "none") + 
  theme(legend.text=element_text(size=4)) + 
  labs(x = "", y = "Proportion of proteins with this annotation") 
ggsave(filename = sprintf("%sFigure3/annotations.at.low.cov.jpg", 
                          OUTPUT.FIGURES.PATH) ,p.annot.low.cov , width = 15, height = 12)





annots.within.proteins.with.significant.higher.mosaic = annot.stats.per.category.and.mosaicism %>%
   filter(corrected.pval < 0.05 & odds.ratio > 1) %>%
  select(annotation, category, mosaic, prop.proteins.has.this.annot, odds.ratio, corrected.pval) %>%
   arrange(desc(odds.ratio))
write.xlsx(x = annots.within.proteins.with.significant.higher.mosaic, 
           file = sprintf("%stables/Supplementary_table_mosaic_vs_ninmosaic.xlsx", OUTPUT.FIGURES.PATH), 
           sheetName = "Annotations in mosaic vs non-mosaic proteins", 
  col.names = TRUE, row.names = TRUE, append = TRUE)


ss=annot.stats.per.category.and.mosaicism %>%
  arrange(desc(odds.ratio)) %>%
  filter(corrected.pval < 0.05) %>%
  head(60) %>%
  mutate(mosaic = if_else(mosaic, "Mosaic", "Not mosaic"))
  
ss$mosaic = factor(ss$mosaic, levels = c("Not mosaic", "Mosaic"))
ss$annotation = factor(ss$annotation, levels = unique(ss %>% arrange((odds.ratio)) %>% pull(annotation)))

p.odds.low.cov = ggplot(ss  %>% distinct(annotation, category, odds.ratio), 
                        aes(x=annotation, y = odds.ratio, fill = category)) +
  geom_bar(stat="identity", width = 0.8) + 
  scale_fill_manual(values = PHROG.COLOR.MAP) +
  theme_minimal() + 
  #guides(fill = "none") + 
  theme(legend.text=element_text(size=8)) + 
  labs(x = "", y = "Odds ratio", fill = "category") + 
  coord_flip() 
p.odds.low.cov
ggsave(filename = sprintf("%sFigure3/low.cov.odds.ratio.jpg", OUTPUT.FIGURES.PATH) ,p.odds.low.cov , width = 10, height = 7)


p.low.cov = ggplot(ss, aes(x=annotation, y = prop.proteins.has.this.annot, alpha = mosaic, fill = category)) +
  geom_bar(stat="identity", position = position_dodge2(width = 0.8, preserve = "single"), col = "black") + 
  scale_fill_manual(values = PHROG.COLOR.MAP) +
  #scale_color_manual(values = PHROG.COLOR.MAP) +
  guides(col = "none") +
  scale_alpha_manual(values = c("Mosaic" = 1, "Not mosaic" = 0.4)) +
  #facet_grid(.~mosaic) +
  theme_minimal() + 
  guides(fill = "none", color = "none") + 
  theme(legend.text=element_text(size=4)) + 
  labs(x = "", y = "Proportion of proteins with this annotation", fill = "category") + 
  coord_flip() 
p.low.cov
ggsave(filename = sprintf("%sFigure3/low.cov.funct.all.proteins.jpg", OUTPUT.FIGURES.PATH) ,p.low.cov , width = 15, height = 12)


```


# new Fif 3c shared domains by mosaic pairs (known and unknown)
```{r}
domains.shared.in.mosaic.pairs = data.table::fread(file = sprintf("%sFigure3/domains-shared-by-mosaic-pairs.txt", OUTPUT.FIGURES.PATH))

included.ecods = domains.shared.in.mosaic.pairs %>% 
  filter(prop.protein.pairs >= 0.005) %>%
  pull(t_id)

ecod.table <- domains.shared.in.mosaic.pairs %>% 
  filter(t_id %in% included.ecods)%>%
  arrange(prop.protein.pairs)

ecod.table$t_name = factor(ecod.table$t_name, 
                           levels = ecod.table %>% pull(t_name) %>% unique())

display.h.name <- ecod.table$h_name
display.h.name[ecod.table$t_name == ecod.table$h_name] <- "same"
display.t.name <- sprintf("%s\n(H: %s)", ecod.table$t_name, display.h.name)

getPalette <- colorRampPalette(RColorBrewer::brewer.pal(9, "Set1"))
no.hom <- length(unique(ecod.table$h_name))
p.shared.ecods <- ggplot(data=ecod.table, aes(x=t_name, y=prop.protein.pairs, fill=h_name)) + 
  geom_bar(stat="identity", position = position_dodge2(width = 0.9, preserve = "single"),
           alpha = 1, color="black") +#, fill = "gray90") +
  scale_x_discrete(breaks = ecod.table$t_name, labels = display.t.name) +
  theme_minimal() + theme(legend.text=element_text(size=6)) +
  labs(x = "", y = "Proportion of representative proteins pairs") + 
  guides(fill = "none", color = "none") + 
  coord_flip()

p.shared.ecods
#p.panelc <- plot_grid(p.seq, p.ecod, labels = c("C", "D"), label_size = 25, ncol = 2)
ggsave(filename = sprintf("%sFigure3/folds_shared_by_mosaic_proteins.jpg", OUTPUT.FIGURES.PATH), p.shared.ecods, width = 12, height = 6)

```


# Fig 3c shared ecods in knwona and unknown prots
```{r}
domains.within.proteins = data.table::fread(file = sprintf("%sFigure3/domains-in-known-and-unknown.txt", OUTPUT.FIGURES.PATH))


domains.within.proteins.with.significant.higher.mosaic = domains.within.proteins %>%
   filter(corrected.pval < 0.05 & odds.ratio > 1) %>%
  select(t_id, t_name, mosaic, prop.proteins.with.this.ecod.hit = freq.q, odds.ratio, corrected.pval) %>%
   arrange(desc(odds.ratio))
write.xlsx(x = domains.within.proteins.with.significant.higher.mosaic, 
           file = sprintf("%stables/Supplementary_table_mosaic_vs_ninmosaic.xlsx", OUTPUT.FIGURES.PATH), 
           sheetName = "Domains in mosaic vs non-mosaic proteins", 
  col.names = TRUE, row.names = TRUE, append = TRUE)


included.ecods = domains.within.proteins %>% 
  filter(corrected.pval < 0.05) %>%
  arrange(desc(odds.ratio)) %>%
  head(30) %>%
  #filter(freq.q >= 0.025) %>%
  pull(t_id) %>% unique()

ecod.table <- domains.within.proteins %>% 
  filter(t_id %in% included.ecods)%>%
  arrange(mosaic, odds.ratio)

ecod.table$t_name = factor(ecod.table$t_name, 
                           levels = ecod.table %>% filter(mosaic == "Mosaic") %>% arrange(odds.ratio) %>% pull(t_name) %>% unique())
ecod.table$mosaic = factor(ecod.table$mosaic, levels = c("Not mosaic", "Mosaic"))

display.h.name <- ecod.table$h_name
display.h.name[ecod.table$t_name == ecod.table$h_name] <- "same"
display.t.name <- sprintf("%s\n(H: %s)", ecod.table$t_name, display.h.name)

getPalette <- colorRampPalette(RColorBrewer::brewer.pal(9, "Set1"))
no.hom <- length(unique(ecod.table$h_name))
p <- ggplot(data=ecod.table, aes(x=t_name, y=freq.q, alpha = mosaic)) + #fill=h_name, 
  geom_bar(stat="identity", position = position_dodge2(width = 0.9, preserve = "single"), col = "black")
#p <- p + scale_fill_manual(values = getPalette(no.hom)) +
#  scale_color_manual(values = getPalette(no.hom))
p <- p + scale_x_discrete(breaks = ecod.table$t_name, labels = display.t.name)
p <- p + theme_minimal() + theme(legend.text=element_text(size=4))
p <- p + labs(x = "", y = "Proportion of representative proteins")
p <- p + guides(fill = "none", color = "none", alpha = "none") + 
  scale_alpha_manual(values = c("Mosaic" = 1, "Not mosaic" = 0.3))
p.domains <- p + coord_flip()
p.domains

#p.panelc <- plot_grid(p.seq, p.ecod, labels = c("C", "D"), label_size = 25, ncol = 2)
ggsave(filename = sprintf("%sFigure3/folds_within_mosaic_proteins.jpg", OUTPUT.FIGURES.PATH), p.domains, width = 12, height = 12)


p.odds = ggplot(ecod.table %>% distinct(t_name, odds.ratio), aes(x=t_name, y = odds.ratio)) +
  geom_bar(stat="identity", width = 0.8, fill = "gray90", col = "black") + 
  scale_x_discrete(breaks = ecod.table$t_name, labels = display.t.name) +
  theme_minimal() + 
  guides(fill = "none") + 
  theme(legend.text=element_text(size=4)) + 
  labs(x = "", y = "Odds ratio", fill = "category") + 
  coord_flip() 
p.odds
ggsave(filename = sprintf("%sFigure3/folds_within_mosaic_proteins.odds.ratio.jpg", OUTPUT.FIGURES.PATH) ,p.odds , width = 15, height = 12)
```





# Density plot: Figure 3a
```{r} 
annotated.hhr.table = data.table::fread(sprintf("%sFigure3/cov.vs.pident.txt", OUTPUT.FIGURES.PATH))
spectral.scale = rev(RColorBrewer::brewer.pal(11, "Spectral"))
fig3a = ggplot() + 
  stat_binhex(data = annotated.hhr.table, bins = 50, aes(x=pident, y=max.cov)) + 
  geom_rect(aes(xmin = MINIMUM.PIDENT.FOR.PAIRWISE.HIT/100, xmax = 1, 
            ymin = 0, ymax = MINIMUM.COV.FOR.PROTEIN.SIMILARITY, 
            color = "red"), fill = NA, size = 2) + guides(color = "none") +
  geom_text(aes(x = mean(c(MINIMUM.PIDENT.FOR.PAIRWISE.HIT/100, 1)), 
                y = mean(c(0, MINIMUM.COV.FOR.PROTEIN.SIMILARITY)), 
                label = "Mosaic\n pairs", col = "red")) +
  scale_fill_gradientn(colours = spectral.scale) + 
  scale_x_continuous(limits = c(0,1)) + 
  scale_y_continuous(limits = c(0,1)) + 
  theme_bw() + 
  labs(x = "Percentage identity", y = "Pairwise sequence coverage", fill = "no. pairs")
fig3a
ggsave(sprintf("%s/Figure3/panelA_pairwise-seq.png", OUTPUT.FIGURES.PATH), fig3a,  width = 5, height = 4)
  
```

#join fig 3 panels
```{r}
fig3ab = plot_grid(fig3a, p.shared.ecods, labels = c("A", "B"), label_size = 25, ncol = 2, rel_widths = c(0.4, 0.6))
ggsave(sprintf("%s/Figure3/panelAB.pdf", OUTPUT.FIGURES.PATH), fig3ab,  width = 14, height = 5)
fig3de = plot_grid(p.domains, p.low.cov, labels = c("D", "E"), label_size = 25, ncol = 2,rel_widths = c(0.5, 0.5))
ggsave(sprintf("%s/Figure3/panelDE.pdf", OUTPUT.FIGURES.PATH), fig3de,  width = 15, height = 6)

fig3bc = plot_grid(p.odds, p.odds.low.cov, labels = c("B", "C"), label_size = 25, ncol = 2,rel_widths = c(0.4, 0.6))
ggsave(sprintf("%s/Figure3/panelBC.pdf", OUTPUT.FIGURES.PATH), fig3bc,  width = 15, height = 6)

```



#### Alternative versions of our figures
# FIG 3 CD mosaic unknowns
```{r}
## unknowns
table.unknowns.seq.filename <- sprintf("%sFigure_Alternatives/table-unknown-seq.txt", OUTPUT.FIGURES.PATH) 
table.unknowns.seq <- data.table::fread(table.unknowns.seq.filename) %>%
  filter(weight >= 15) %>%
  arrange(weight)

# plot sequence
table.unknowns.seq$category[table.unknowns.seq$category == "unknown"] <- "other"
table.unknowns.seq$annotation <- factor(table.unknowns.seq$annotation, levels = unique(table.unknowns.seq$annotation))

p.seq <- ggplot(data=table.unknowns.seq, aes(x=annotation, y=weight, fill=category)) + 
  geom_bar(stat="identity") + 
  scale_fill_manual(values = PHROG.COLOR.MAP) + 
  theme_minimal() + 
  theme(legend.text=element_text(size=6)) + 
  labs(x = "", y = "weighted occurrence", fill = "category") + 
  coord_flip()
p.seq
ggsave(filename = sprintf("%sFigure_Alternatives/Functions_of_unknown_prots_with_seq_mosaicism_signal.jpg", OUTPUT.FIGURES.PATH) , p.seq, width = 6, height = 5)


# plot sequence: all not only mosaic
table.all.unknowns.seq.filename <- sprintf("%sFigure_Alternatives/table-all-unknown-seq.txt", OUTPUT.FIGURES.PATH) 
table.all.unknowns.seq <- data.table::fread(table.all.unknowns.seq.filename) %>%
  filter(weight >= 50) %>%
  arrange(weight)

table.all.unknowns.seq$category[table.all.unknowns.seq$category == "unknown"] <- "other"
table.all.unknowns.seq$annotation <- factor(table.all.unknowns.seq$annotation, levels = unique(table.all.unknowns.seq$annotation))

p.seq.supp <- ggplot(data=table.all.unknowns.seq, aes(x=annotation, y=weight, fill=category)) + 
  geom_bar(stat="identity") + 
  scale_fill_manual(values = PHROG.COLOR.MAP) + 
  theme_minimal() + 
  theme(legend.text=element_text(size=6)) + 
  labs(x = "", y = "weighted occurrence", fill = "category") + 
  coord_flip() + 
  scale_y_log10()
p.seq.supp
ggsave(filename = sprintf("%sFigure_Alternatives/Functions_of_all_unknown_prots.jpg", OUTPUT.FIGURES.PATH) , p.seq.supp, width = 10, height = 10)

# plot ecod
table.unknowns.ecod.filename <- sprintf("%sFigure_Alternatives/table-unknown-ecod.txt", OUTPUT.FIGURES.PATH)
table.unknowns.ecod <- fread(table.unknowns.ecod.filename)

ecod.table <- table.unknowns.ecod %>% 
  filter(freq.q>=0.005) %>%
  arrange(freq.q)
ecod.table$t_name <- factor(ecod.table$t_name, levels = unique(ecod.table$t_name))

ecod.table$h.index <- sapply(1:nrow(ecod.table), function(index){
  this.topology <- ecod.table$t_id[index]
  this.topology.h.index <- strsplit(this.topology, ".", fixed = T)[[1]]
  this.topology.h.index <- this.topology.h.index[-length(this.topology.h.index)]
  this.topology.h.index <- as.character(paste(this.topology.h.index, collapse = "."))
})
ecod.table = ecod.table %>%
    left_join(ecod_id_to_names_map %>% filter(level == "H") %>% select(h.index = id, h_name = name))
display.h.name <- ecod.table$h_name
display.h.name[ecod.table$t_name == ecod.table$h_name] <- "same"
display.t.name <- sprintf("%s\n(H: %s)", ecod.table$t_name, display.h.name)

getPalette <- colorRampPalette(RColorBrewer::brewer.pal(9, "Set1"))
no.hom <- length(unique(ecod.table$h_name))
p <- ggplot(data=ecod.table, aes(x=t_name, y=freq.q, fill=h_name)) + geom_bar(stat="identity")
p <- p + scale_fill_manual(values = getPalette(no.hom))
p <- p + scale_x_discrete(breaks = ecod.table$t_name, labels = display.t.name)
p <- p + theme_minimal()
p <- p + labs(x = "", y = "frequency")
p <- p + guides(fill = "none")
p.ecod <- p + coord_flip()
p.ecod
ggsave(filename = sprintf("%sFigure_Alternatives/Folds_shared_by_unknown_poteins_with_domain_signal.jpg", OUTPUT.FIGURES.PATH) , p.seq.supp, width = 10, height = 10)


```